export interface Series {
  id: string;
  title: string;
  year: string;
  genre: string[];
  rating: number;
  seasons: number;
  description: string;
  image: string;
  status: "Ended" | "Ongoing" | "Upcoming";
}

export const seriesDatabase: Series[] = [
  {
    id: "1",
    title: "Breaking Bad",
    year: "2008–2013",
    genre: ["Crime", "Drama", "Thriller"],
    rating: 9.5,
    seasons: 5,
    description: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
    image: "https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=400&h=600&fit=crop",
    status: "Ended",
  },
  {
    id: "2",
    title: "Game of Thrones",
    year: "2011–2019",
    genre: ["Action", "Adventure", "Drama"],
    rating: 9.2,
    seasons: 8,
    description: "Nine noble families fight for control over the lands of Westeros while an ancient enemy returns.",
    image: "https://images.unsplash.com/photo-1534809027769-b00d750a6bac?w=400&h=600&fit=crop",
    status: "Ended",
  },
  {
    id: "3",
    title: "Stranger Things",
    year: "2016–2025",
    genre: ["Drama", "Fantasy", "Horror"],
    rating: 8.7,
    seasons: 5,
    description: "When a young boy disappears, his mother and friends must confront terrifying supernatural forces.",
    image: "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?w=400&h=600&fit=crop",
    status: "Ended",
  },
  {
    id: "4",
    title: "The Mandalorian",
    year: "2019–",
    genre: ["Action", "Adventure", "Sci-Fi"],
    rating: 8.6,
    seasons: 3,
    description: "The travels of a lone bounty hunter in the outer reaches of the galaxy.",
    image: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=400&h=600&fit=crop",
    status: "Ongoing",
  },
  {
    id: "5",
    title: "Dark",
    year: "2017–2020",
    genre: ["Crime", "Drama", "Mystery"],
    rating: 8.8,
    seasons: 3,
    description: "A family saga with a supernatural twist set in a German town where the disappearance of two children exposes the relationships among four families.",
    image: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=400&h=600&fit=crop",
    status: "Ended",
  },
  {
    id: "6",
    title: "The Last of Us",
    year: "2023–",
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.8,
    seasons: 2,
    description: "Joel and Ellie must survive in a post-apocalyptic world ravaged by a fungal infection.",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=600&fit=crop",
    status: "Ongoing",
  },
  {
    id: "7",
    title: "Chernobyl",
    year: "2019",
    genre: ["Drama", "History", "Thriller"],
    rating: 9.4,
    seasons: 1,
    description: "The true story of one of the worst man-made catastrophes in history.",
    image: "https://images.unsplash.com/photo-1580982324076-d95230f6e024?w=400&h=600&fit=crop",
    status: "Ended",
  },
  {
    id: "8",
    title: "Severance",
    year: "2022–",
    genre: ["Drama", "Mystery", "Sci-Fi"],
    rating: 8.7,
    seasons: 2,
    description: "An employee at a corporation undergoes a procedure that separates work and personal memories.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=600&fit=crop",
    status: "Ongoing",
  },
  {
    id: "9",
    title: "True Detective",
    year: "2014–2024",
    genre: ["Crime", "Drama", "Mystery"],
    rating: 8.9,
    seasons: 4,
    description: "Seasonal anthology series where police investigations unearth personal and professional secrets.",
    image: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400&h=600&fit=crop",
    status: "Ended",
  },
  {
    id: "10",
    title: "The Bear",
    year: "2022–",
    genre: ["Comedy", "Drama"],
    rating: 8.6,
    seasons: 3,
    description: "A young chef from the fine dining world returns to Chicago to run his family's sandwich shop.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=600&fit=crop",
    status: "Ongoing",
  },
  {
    id: "11",
    title: "Succession",
    year: "2018–2023",
    genre: ["Comedy", "Drama"],
    rating: 8.8,
    seasons: 4,
    description: "The Roy family controls one of the biggest media conglomerates. When the patriarch considers retirement, each sibling begins jockeying for position.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&h=600&fit=crop",
    status: "Ended",
  },
  {
    id: "12",
    title: "Arcane",
    year: "2021–2024",
    genre: ["Animation", "Action", "Adventure"],
    rating: 9.0,
    seasons: 2,
    description: "Set in the utopian region of Piltover and the oppressed underground of Zaun.",
    image: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=400&h=600&fit=crop",
    status: "Ended",
  },
  {
    id: "13",
    title: "Better Call Saul",
    year: "2015–2022",
    genre: ["Crime", "Drama"],
    rating: 9.0,
    seasons: 6,
    description: "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to Breaking Bad.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&h=600&fit=crop",
    status: "Ended",
  },
  {
    id: "14",
    title: "The Witcher",
    year: "2019–",
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.0,
    seasons: 3,
    description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=600&fit=crop",
    status: "Ongoing",
  },
  {
    id: "15",
    title: "Fleabag",
    year: "2016–2019",
    genre: ["Comedy", "Drama"],
    rating: 8.7,
    seasons: 2,
    description: "A dry-witted woman navigates life in London while dealing with a recent tragedy.",
    image: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=400&h=600&fit=crop",
    status: "Ended",
  },
  {
    id: "16",
    title: "House of the Dragon",
    year: "2022–",
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.4,
    seasons: 2,
    description: "An internal succession war within House Targaryen at the height of its power, 172 years before Daenerys.",
    image: "https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?w=400&h=600&fit=crop",
    status: "Ongoing",
  },
];
